Description: "Creates a Linux operator machine."
Mappings:
  Images:
    us-east-1:
      Id: "ami-04505e74c0741db8d"
    us-east-2:
      Id: "ami-0fb653ca2d3203ac1"
    us-west-1:
      Id: "ami-01f87c43e618bf8f0"
    us-west-2:
      Id: "ami-017fecd1353bcc96e"
Parameters:
  VpcId:
    Type: String
  OperatorName:
    Type: String
    Default: cloud-operator
    AllowedValues:
      - cloud-operator
      - cloud-operator-1
      - cloud-operator-2
      - cloud-operator-3
      - cloud-operator-4
      - cloud-operator-5
Resources:
  OperatorKeyPair:
    Type: 'AWS::EC2::KeyPair'
    Properties:
      KeyName: cloud-operator-keypair
  OperatorSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: Security Group for AMIs
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
  OperatorInstance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !FindInMap
        - Images
        - !Ref AWS::Region
        - Id
      InstanceType: "t3.large"
      KeyName: !Ref OperatorKeyPair
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 50
            DeleteOnTermination: true
      SecurityGroupIds:
        - !Ref OperatorSecurityGroup
      Tags:
        - Key: "Name"
          Value: !Ref OperatorName
Outputs:
  InstanceId:
    Value: !Ref OperatorInstance
  PublicDnsName:
    Value: !GetAtt OperatorInstance.PublicDnsName

